---
pagetitle: "DEO_index_Fall2019"
output: html_document
---
<br>
<br>

# Welcome to **Dynamic Economic Optimization** - Fall 2019  
  
<br>

### Course Objective
  
The purpose of the course is to study the applications of optimization models in agricultural and natural resource economics. Our focus is to develop the ability to formulate economizing problems mathematically, and learn computer algorithms to solve various types of optimization problems in agricultural production and natural resource management. Students will learn computer algorithms solving linear and nonlinear programming models, deterministic and stochastic dynamic models, and machine learning models.

<br>

### Course Text

The primary text used in this class is:

Miranda, M. J., & Fackler, P. L. (2002). Applied Computational Economics and Finance (P. L. Fackler, ed.). Cambridge, Mass. : MIT Press.

<br>
  
**Professor of Record:**   Chenggang Wang, PhD  

**Office:**  Ag Sciences 301C

**Phone:**  (806) 742-0261 ext. 238

**E-mail:**  chenggang.wang@ttu.edu

**Meeting Times:** MW 1:00 – 2:20 pm @ AGRI 208

**Office Hours:**  MW 2:30 – 3:30 pm or any other time with an appointment

<br>

**Teaching Assistant:**  Matthew Aaron Looney, MS

**Office:**  Ag Sciences 205C

**E-mail:**  matthew.looney@ttu.edu

**Office Hours:**  MW 2:30 – 3:30 pm or any other time with an appointment

<br>

<center>
<a href="DEO_main_Fall2019.html"><font size="4"> Course Laboratory Website</font>

<br>
<br>
<br>

