---
output: html_document
---
<br>
<br>

<center>
# **AAEC 6305: Dynamic Economic Optimization** - Fall 2019  
</center>

<br>

### Course Objective

The purpose of the course is to study the applications of optimization models in economics.  Our focus of study is to develop the ability to formulate economizing problems as well-defined optimization problems, solve them algebraically or with the aid of optimization software, and interpret the solutions.  Theoretical development of optimization techniques is not emphasized in this course.  

<br>

* Syllabus [(pdf)](pdf/Syllabus _AAEC6305_Fall2019.pdf)  

<br>

* Getting Started with MATLAB and Python
  -  Week 1-2: Introduction to MATLAB, Python and Optimization Routines
      -  <font size="2"> Homework 1 </font>
      
<br>

* Introduction to Optimization Models
  -  Week 3: Optimization models  
  
<br>

* Static Optimization Models for LP and NLP Problems
  -  Week 4: Linear and Nonlinear Static models
      - <a class="reference download internal" download="" href="Optim_Class_Fall2019/Cournot_oligopolist_problem.ipynb"><font size="2">Cournot Oligopoly Model</font></a>
      - <a class="reference download internal" download="" href="Optim_Class_Fall2019/Broydens_Method.ipynb"><font size="2">Broyden's Method</font></a>
      -  <font size="2"> Homework 2 </font>

  
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
